-- admin user=postgres

-- PLC
CREATE DATABASE plc;
GRANT ALL PRIVILEGES ON DATABASE plc TO postgres;

-- BGS
CREATE DATABASE bgs;
GRANT ALL PRIVILEGES ON DATABASE bgs TO postgres;
CREATE DATABASE carstore;
GRANT ALL PRIVILEGES ON DATABASE carstore TO postgres;

-- bsky(AppView)
CREATE DATABASE bsky;
GRANT ALL PRIVILEGES ON DATABASE bsky TO postgres;

-- palomar(search)
CREATE DATABASE palomar;
GRANT ALL PRIVILEGES ON DATABASE palomar TO postgres;

-- pds
--CREATE DATABASE pds;
--GRANT ALL PRIVILEGES ON DATABASE pds TO postgres;

-- ozone(Moderation)
CREATE DATABASE ozone;
GRANT ALL PRIVILEGES ON DATABASE ozone TO postgres;
